---
title: "rbind"
---


# import dat

```{r}

#Other_Weather
url_Other_Weather <- 
  "https://raw.githubusercontent.com/statistikZH/covid19monitoring_other_Weather/master/Other_Weather.csv"
Other_Weather <- read.csv(url(url_Other_Weather), header=T, sep=",", stringsAsFactors=FALSE, encoding="UTF-8")

#Mobility_VBZHardbruecke
url_VBZHardbruecke <- "https://raw.githubusercontent.com/statistikZH/covid19monitoring_mobility_VBZHardbruecke/master/Mobility_VBZHardbruecke.csv"
Mobility_VBZHardbruecke <- read.csv(url(url_VBZHardbruecke), header=T, sep=",", stringsAsFactors=FALSE, encoding="UTF-8")

#Mobility_Intervista
url_Mobility_Intervista  <-
  "https://raw.githubusercontent.com/statistikZH/covid19monitoring_mobility_intervista/master/Mobility_Intervista.csv"
Mobility_Intervista <- read.csv(url(url_Mobility_Intervista), header=T, sep=",", stringsAsFactors=FALSE, encoding="UTF-8")

#Economy_SMI
url_Economy_SMI <-
  "https://raw.githubusercontent.com/statistikZH/covid19monitoring_economy_SMI/master/Economy_SMI.csv"
Economy_SMI <- read.csv(url(url_Economy_SMI), header=T, sep=",", stringsAsFactors=FALSE, encoding="UTF-8")

#Economy_FlightTrafficZRH
url_Economy_FlightTrafficZRH <-
  "https://raw.githubusercontent.com/statistikZH/covid19monitoring_economy_FlightTraffic/master/Economy_FlightTraffic.csv"
Economy_FlightTrafficZRH <- read.csv(url(url_Economy_FlightTrafficZRH), header=T, sep=",", stringsAsFactors=FALSE, encoding="UTF-8")

#Economy_SIX
url_Economy_SIX <-
  "https://raw.githubusercontent.com/statistikZH/covid19monitoring_economy_SIX/master/Economy_SIX.csv"
Economy_SIX <- read.csv(url(url_Economy_SIX), header=T, sep=",", stringsAsFactors=FALSE, encoding="UTF-8")

#Education_Mindmaps
url_Education_Mindmaps <-
  "https://raw.githubusercontent.com/bildungsmonitoringZH/covid19_edu_mindsteps/master/Bildung_LernplattformMindsteps.csv"
Education_Mindmaps <- read.csv(url(url_Education_Mindmaps), header=T, sep=",", stringsAsFactors=FALSE, encoding="UTF-8")

#Education_LMVZ
url_Education_LMVZ <-
"https://raw.githubusercontent.com/bildungsmonitoringZH/covid19_edu_lmvzmath/master/Bildung_TrainingMathematik.csv?token=AO5R67TWCP3FU6EHMGONFSS6RM752"
Education_LMVZ <- read.csv(url(url_Education_LMVZ), header=T, sep=",", stringsAsFactors=FALSE, encoding="UTF-8")


```


# rbind

```{r}

covid19monitoring <- rbind(Other_Weather, Mobility_VBZHardbruecke, Mobility_Intervista, Economy_SMI, Economy_FlightTrafficZRH, Economy_SIX, Education_Mindmaps, Education_LMVZ)

```

# Validation

```{r}

source("./function.R")

write.table(covid19monitoring, "Validation/ValidationData.csv", sep=",", fileEncoding="UTF-8", row.names = F)
ValidationMetadata()

```

# daily update

```{r}

source("./function.R")

file.copy("Validation/ValidationData.csv", "./covid19socialmonitoring.csv", overwrite = TRUE)
file.copy("Validation/ValidationMetadata.csv", "./Metadata.csv", overwrite = TRUE)


```

